---
title: "Takehome 1 Correlations"
output: html_document
---

#  Due: 2/3
<br>
Turn in via email to: Homewor.89prji5a8z9gh76d@u.box.com  by attaching 1) an rmd or a rnw file of your code and answers and 2) a pdf of said file. Use your last name to label the files (e.g,. "Jackson_takehome1") and include your name as part of the document front/top-matter (YAML).  
<br>
All take home projects are **INDEPENDENT** projects; do not share code or answers.   
<br>
Note: "by hand" means using the formulas to calculate the answers. This is contrasted with the simpler way of using R functions. It is recommended to use R functions if the "by hand" method is not explicitly stated. 
<br>
<br>

Data are available via github for this class https://github.com/josh-jackson/5067-Spring-2020 
Raw score available here: 
https://raw.githubusercontent.com/josh-jackson/5067-Spring-2020/master/HW_1.csv

1. Load the HW_1 data into R. Create a 1) an informative plot/figure of the study variables and 2) a informative descriptives table of the study variables. These should be the types of figure and table that you could publish in a journal article.  

2. Run a 1) t-test, 2) one way anova, 3) linear model (regression) with dummy codes, 4)  linear model with effect coding, and 5) correlation between two variables using the HW_1 data. For the dummy code model, interpret the intercept and regression coefficient. 

3. What similarities do you see across these tests? Differences?  

4. What is the Coefficient of Determination for your dummy code model above? Interpret.  

5. "By hand," (using the output from #2 and the scores obtained from the dataframe) calculate the predicted (fitted) scores and the residuals for subject #3 and #5 using dummy coding. Then calculate their predicted and residual score with the effect codes. Are they the same? Explain why or why not. 

6. For the dummy coded model, graph a distribution of the residuals. Then test whether the residuals correlated with X. Explain why they are/are not. 

7. In #2, the t-test output gives you a confidence interval for the difference between the two groups. Using the dummy coded summary output, calculate this same confidence interval.  

## THE QUESTIONS BELOW DO NOT INVOLVE HW_1 DATA:

7. You are contacted by the deans office. They ran a correlation between Wash U SAT scores and happiness and found a correlation of r = .21061 with a sample of N = 600. They want to know if this is lower than a published meta-analytic estimate (.2554)? Do this "by hand". Treat the meta-analytic estimate as the "population". 

4. Create a 95% confidence interval around r = .30 "by hand" for sample sizes of N = 50 and N = 500. Interpret each CI in your own words and compare and contrast the two CIs.   







